#! /bin/bash

source variables

mkdir -p BAM2 Temp

function prep {
  sample_prefix="$1"  

  if [ ! -f BAM2/${sample_prefix}.bam ]
  then
  docker run \
    -v /tmp/bwa:/data/bam_files \
    -v /tmp/sorted:/data/output_data \
    --user $(id -u):$(id -g) \
    --rm \
    srp33/somatic_wgs:latest \
    sort_bam \
      -b $sampleID.bam \
      -o $sampleID.bam \
      -t $num_threads

  docker run \
    -v /tmp/sorted:/data/bam_files \
    --user $(id -u):$(id -g) \
    --rm \
    srp33/somatic_wgs:latest \
    index_bam \
      -b $sampleID.bam \
      -t $num_threads

  docker run \
    -v /tmp/sorted:/data/bam_files \
    -v /tmp/marked:/data/output_data \
    --user $(id -u):$(id -g) \
    --rm \
    srp33/somatic_wgs:latest \
    mark_duplicates \
      -b $sampleID.bam \
      -o $sampleID.bam \
      -t $num_threads

  docker run \
    -v /tmp/marked:/data/bam_files \
    -v /tmp/read_groups:/data/output_data \
    --user $(id -u):$(id -g) \
    --rm \
    srp33/somatic_wgs:latest \
    add_read_groups \
      -b $sampleID.bam \
      -o $sampleID.bam \
      -id $sampleID \
      -lb $sampleID \
      -s $sampleID

  docker run \
    -v /tmp/read_groups:/data/bam_files \
    --user $(id -u):$(id -g) \
    --rm \
    srp33/somatic_wgs:latest \
    index_bam \
      -b $sampleID.bam \
      -t $num_threads
  fi
}

prep TCRBOA7-N-WEX
prep TCRBOA7-T-WEX
prep TCRBOA7-N-WGS.lane1
prep TCRBOA7-N-WGS.lane2
prep TCRBOA7-T-WGS.lane1
prep TCRBOA7-T-WGS.lane2
prep TCRBOA7-T-WGS.lane3
prep TCRBOA7-T-WGS.lane4
