#! /bin/bash

set -o errexit

source variables

function mark {
  bam_file="$1"

  docker run \
    -v $(pwd)/BAM:/data/bam_files \
    -v $(pwd)/Temp:/data/output_data \
    --user $(id -u):$(id -g) \
    --rm \
    srp33/somatic_wgs:$tag \
    mark_duplicates \
      -b "$bam_file" \
      -o "$bam_file" \
      -t $num_threads
}

mkdir -p Temp
rm -rf Temp/*

for f in BAM/*.bam
do
  mark $(basename $f)
done

mv Temp/*.bam* BAM/
rmdir Temp
