#! /bin/bash

set -o errexit

source variables

function recal {
  bam_file="$1"

  docker run \
    -v $(pwd)/BAM:/data/bam_files \
    -v $(pwd)/REF/genome:/data/ref_genome \
    -v $(pwd)/REF/index:/data/ref_index \
    -v $(pwd)/REF/recal:/data/vcf_files \
    -v $(pwd)/Temp:/data/output_data \
    --user $(id -u):$(id -g) \
    --rm \
    srp33/somatic_wgs:$tag \
    base_recalibrator \
      -b $bam_file \
      -r $ref_genome_version.fa \
      -s dbsnp_146.hg38.vcf \
      -s 1000G_phase1.snps.high_confidence.hg38.vcf \
      -s Mills_and_1000G_gold_standard.indels.hg38.vcf \
      -o $bam_file.recal

#  docker run \
#    -v /tmp/read_groups:/data/bam_files \
#    -v /tmp/bqsr:/data/input_data \
#    -v /tmp/bqsr_corrected:/data/output_data \
#    --user $(id -u):$(id -g) \
#    --rm \
#    srp33/somatic_wgs:$tag \
#    apply_bqsr \
#      -b $sampleID.bam \
#      -bqsr $sampleID.recal \
#      -o $sampleID.bam

#  docker run \
#    -v /tmp/bqsr_corrected:/data/bam_files \
#    --user $(id -u):$(id -g) \
#    --rm \
#    srp33/somatic_wgs:$tag \
#    index_bam \
#      -b $sampleID.bam \
#      -t 25
}

mkdir -p Temp
rm -rf Temp/*

for f in BAM/*.bam
do
  recal $(basename $f)
break
done

#mv Temp/*.bam* BAM/
#rmdir Temp
